CREATE TABLE "tokens" (
  "id"      BIGINT AUTO_INCREMENT PRIMARY KEY,
  "user_id" BIGINT,
  "token"   TEXT NOT NULL
);
ALTER TABLE "tokens"
  ADD CONSTRAINT "user_fk" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
  ON UPDATE RESTRICT
  ON DELETE CASCADE;
